"""Maps HTTP GET endpoints to their corresponding response models."""
from woocommerce_pydantic.wcapi.models import wc_collections, wc_resources

RESPONSE_MODELS = {
    "get": {
        "/coupons": wc_collections.ShopCouponList,
        "/coupons/{id}": wc_resources.ShopCoupon,
        "/customers/{customer_id}/downloads": wc_collections.CustomerDownloadList,
        "/customers": wc_collections.CustomerList,
        "/customers/{id}": wc_resources.Customer,
        "/orders/{order_id}/notes": wc_collections.OrderNoteList,
        "/orders/{order_id}/notes/{id}": wc_resources.OrderNote,
        "/orders/{order_id}/refunds": wc_collections.ShopOrderRefundList,
        "/orders/{order_id}/refunds/{id}": wc_resources.ShopOrderRefund,
        "/orders": wc_collections.ShopOrderList,
        "/orders/{id}": wc_resources.ShopOrder,
        "/products/attributes/{attribute_id}/terms": wc_collections.ProductAttributeTermList,
        "/products/attributes/{attribute_id}/terms/{id}": wc_resources.ProductAttributeTerm,
        "/products/attributes": wc_collections.ProductAttributeList,
        "/products/attributes/{id}": wc_resources.ProductAttribute,
        "/products/categories": wc_collections.ProductCatList,
        "/products/categories/{id}": wc_resources.ProductCat,
        "/products/reviews": wc_collections.ProductReviewList,
        "/products/reviews/{id}": wc_resources.ProductReview,
        "/products/shipping_classes": wc_collections.ProductShippingClassList,
        "/products/shipping_classes/{id}": wc_resources.ProductShippingClass,
        "/products/tags": wc_collections.ProductTagList,
        "/products/tags/{id}": wc_resources.ProductTag,
        "/products": wc_collections.ProductList,
        "/products/{id}": wc_resources.Product,
        "/products/{product_id}/variations": wc_collections.ProductVariationList,
        "/products/{product_id}/variations/{id}": wc_resources.ProductVariation,
        "/reports/sales": wc_collections.SalesReportList,
        "/reports/top_sellers": wc_collections.TopSellersReportList,
        "/reports/orders/totals": wc_collections.ReportOrderTotalList,
        "/reports/products/totals": wc_collections.ReportProductTotalList,
        "/reports/customers/totals": wc_collections.ReportCustomerTotalList,
        "/reports/coupons/totals": wc_collections.ReportCouponTotalList,
        "/reports/reviews/totals": wc_collections.ReportReviewTotalList,
        "/reports": wc_collections.ReportList,
        "/shipping/zones": wc_collections.ShippingZoneList,
        "/shipping/zones/{id}": wc_resources.ShippingZone,
        "/shipping/zones/{id}/locations": wc_collections.ShippingZoneLocationList,
        "/shipping/zones/{zone_id}/methods": wc_collections.ShippingZoneMethodList,
        "/shipping/zones/{zone_id}/methods/{instance_id}": wc_resources.ShippingZoneMethod,
        "/taxes/classes": wc_collections.TaxClassList,
        "/taxes/classes/{slug}": wc_resources.TaxClass,
        "/taxes": wc_collections.TaxList,
        "/taxes/{id}": wc_resources.Tax,
        "/webhooks": wc_collections.WebhookList,
        "/webhooks/{id}": wc_resources.Webhook,
        "/system_status": wc_resources.SystemStatus,
        "/system_status/tools": wc_collections.SystemStatusToolList,
        "/system_status/tools/{id}": wc_resources.SystemStatusTool,
        "/shipping_methods": wc_collections.ShippingMethodList,
        "/shipping_methods/{id}": wc_resources.ShippingMethod,
        "/payment_gateways": wc_collections.PaymentGatewayList,
        "/payment_gateways/{id}": wc_resources.PaymentGateway,
        "/data": wc_resources.DataIndex,
        "/data/continents": wc_collections.DataContinentsList,
        "/data/continents/{location}": wc_resources.DataContinents,
        "/data/countries": wc_collections.DataCountriesList,
        "/data/countries/{location}": wc_resources.DataCountries,
        "/data/currencies": wc_collections.DataCurrenciesList,
        "/data/currencies/current": wc_resources.DataCurrencies,
        "/data/currencies/{currency}": wc_resources.DataCurrencies,
    },
}
